// Valid categories: Trending, Rooms, Iconic Cities, Nature, Beaches, Mountains, Swimming Pools, Castles, Camping, Ski Resorts, Vineyards

const sampleListings = [
  // ─── TRENDING ───────────────────────────────────────────────────────────────
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment. Floor-to-ceiling windows, designer furniture, rooftop terrace, and concierge service available 24/7.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    rooms: 3,
    categories: ["Trending", "Iconic Cities", "Rooms"],
    maxGuests: 6,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 90,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Modern Loft in Downtown Manhattan",
    description: "Stay in the heart of the city in this stylish loft apartment. Features exposed brick, high ceilings, and modern amenities. Walking distance to restaurants and nightlife.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "New York City",
    country: "United States",
    rooms: 1,
    categories: ["Trending", "Iconic Cities", "Rooms"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Overwater Villa in Maldives",
    description: "Indulge in luxury in this overwater villa with stunning views of the Indian Ocean. Glass floor panels, private deck, and direct ocean access for snorkeling.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    rooms: 1,
    categories: ["Trending", "Beaches", "Swimming Pools"],
    maxGuests: 2,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Private Island Retreat Fiji",
    description: "Have an entire island to yourself for a truly exclusive vacation. Private chef, boat transfers, snorkeling, and complete privacy in paradise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 10000,
    location: "Fiji Islands",
    country: "Fiji",
    rooms: 6,
    categories: ["Trending", "Beaches", "Swimming Pools"],
    maxGuests: 12,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis with a private pool. Modern Arabian architecture, infinity pool, and stunning desert views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    rooms: 5,
    categories: ["Trending", "Swimming Pools", "Iconic Cities"],
    maxGuests: 10,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── ICONIC CITIES ───────────────────────────────────────────────────────────
  {
    title: "Historic Canal House Amsterdam",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district. Original 17th-century features, modern comfort, and stunning canal views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    rooms: 3,
    categories: ["Iconic Cities", "Trending", "Rooms"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore vibrant Tokyo from this modern, centrally located apartment. High-tech amenities, minimalist design, and easy subway access to all attractions.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    rooms: 2,
    categories: ["Iconic Cities", "Trending", "Rooms"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 90,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach. Original details, modern amenities, and steps from the beach.",
    image: { filename: "listingimage", url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600,
    location: "Miami",
    country: "United States",
    rooms: 2,
    categories: ["Iconic Cities", "Beaches", "Rooms"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone in the heart of Boston. Original hardwood floors, marble fireplaces, and a fully modern kitchen.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Boston",
    country: "United States",
    rooms: 4,
    categories: ["Iconic Cities", "Trending", "Rooms"],
    maxGuests: 8,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Luxury Riad in Marrakech",
    description: "Experience Moroccan luxury in this traditional riad in the heart of Marrakech. Rooftop terrace, courtyard pool, and authentic Moroccan design with modern comforts.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Marrakech",
    country: "Morocco",
    rooms: 4,
    categories: ["Iconic Cities", "Swimming Pools", "Trending"],
    maxGuests: 8,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Eiffel Tower View Apartment",
    description: "Wake up to breathtaking views of the Eiffel Tower in this chic Haussmann apartment. Elegant French interiors, original parquet floors, and a prime location in the 7th arrondissement.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2800,
    location: "Paris",
    country: "France",
    rooms: 2,
    categories: ["Iconic Cities", "Trending", "Rooms"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Colosseum View Terrace Apartment",
    description: "Rare find — a stylish apartment with a private terrace overlooking the Colosseum. Exposed stone walls, modern kitchen, and walking distance to all of ancient Rome.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2600,
    location: "Rome",
    country: "Italy",
    rooms: 2,
    categories: ["Iconic Cities", "Trending", "Rooms"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Heritage Mansion in Havana",
    description: "Step into Cuba's golden era in this restored colonial mansion. Colourful facade, vintage decor, rooftop bar, and just steps from Havana's vibrant old town.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500904156668-758cff89dcff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 900,
    location: "Havana",
    country: "Cuba",
    rooms: 4,
    categories: ["Iconic Cities", "Trending", "Rooms"],
    maxGuests: 8,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Penthouse Suite in Singapore",
    description: "Ultra-modern penthouse suite in the heart of Singapore's financial district. Rooftop plunge pool, infinity city views, and a 15-minute walk to Marina Bay Sands.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3200,
    location: "Singapore",
    country: "Singapore",
    rooms: 3,
    categories: ["Iconic Cities", "Trending", "Swimming Pools"],
    maxGuests: 6,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── NATURE ──────────────────────────────────────────────────────────────────
  {
    title: "Mountain Retreat Cabin in Aspen",
    description: "Unplug and unwind in this peaceful mountain cabin surrounded by nature. Cozy fireplace, mountain views, and hiking trails right outside the door.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1000,
    location: "Aspen",
    country: "United States",
    rooms: 3,
    categories: ["Nature", "Mountains", "Camping"],
    maxGuests: 6,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 2,
    maximumStay: 45,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise with bird watching, forest trails, and complete privacy. Eco-friendly solar power.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 800,
    location: "Portland",
    country: "United States",
    rooms: 1,
    categories: ["Nature", "Camping", "Trending"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Eco-Friendly Treehouse in Costa Rica",
    description: "Stay in an eco-friendly treehouse nestled in the rainforest. Solar powered, rainforest views, and howler monkeys as neighbors. Perfect escape for nature lovers.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 750,
    location: "Manuel Antonio",
    country: "Costa Rica",
    rooms: 1,
    categories: ["Nature", "Camping", "Beaches"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana. Handcrafted log construction, stone fireplace, and abundant wildlife viewing.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1100,
    location: "Montana",
    country: "United States",
    rooms: 2,
    categories: ["Nature", "Mountains", "Camping"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close. All-inclusive with game drives, meals, and expert guides.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    rooms: 2,
    categories: ["Nature", "Trending", "Camping"],
    maxGuests: 4,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 3,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Rainforest Villa in Borneo",
    description: "Immerse yourself in Borneo's ancient rainforest from this elevated villa. Spot wild orangutans, river boat tours, and guided jungle treks. True wilderness in comfort.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1448375240586-882707db888b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1400,
    location: "Kota Kinabalu",
    country: "Malaysia",
    rooms: 2,
    categories: ["Nature", "Camping", "Trending"],
    maxGuests: 4,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Hobbit-Style Earth House in New Zealand",
    description: "Sleep in a magical earth house built into a hillside in rural New Zealand. Curved interiors, meadow views, and complete seclusion. A fairy-tale retreat for two.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 680,
    location: "Matamata",
    country: "New Zealand",
    rooms: 1,
    categories: ["Nature", "Trending", "Camping"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Northern Lights Glass Cabin in Finland",
    description: "Sleep under the stars in a heated glass cabin in Finnish Lapland. Watch the aurora borealis from your bed, enjoy snowshoeing, and soak in an outdoor hot tub.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Rovaniemi",
    country: "Finland",
    rooms: 1,
    categories: ["Nature", "Trending", "Camping"],
    maxGuests: 2,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 3,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── BEACHES ─────────────────────────────────────────────────────────────────
  {
    title: "Cozy Beachfront Cottage in Malibu",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Stunning ocean views and easy beach access. Perfect for couples or small families.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.1.0&auto=format&fit=crop&q=60&w=1000" },
    price: 1500,
    location: "Malibu",
    country: "United States",
    rooms: 2,
    categories: ["Beaches", "Nature", "Rooms"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Beachfront Paradise Villa in Cancun",
    description: "Step out of your door onto the sandy beach. Infinity pool, ocean views, and luxury amenities. The ultimate Caribbean escape.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1613977257365-aaae5a9817ff?ixlib=rb-4.1.0&auto=format&fit=crop&q=60&w=1000" },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    rooms: 4,
    categories: ["Beaches", "Swimming Pools", "Trending"],
    maxGuests: 8,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool. Traditional Balinese architecture, tropical garden, and ocean views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Seminyak, Bali",
    country: "Indonesia",
    rooms: 2,
    categories: ["Beaches", "Swimming Pools", "Trending"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 3,
    maximumStay: 90,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Beachfront Villa in Mykonos",
    description: "Enjoy the crystal-clear waters of the Mediterranean in this beautiful villa. Whitewashed walls, blue domes, and spectacular sunset views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    rooms: 3,
    categories: ["Beaches", "Trending", "Swimming Pools"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 4,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to a secluded beach house on the Pacific coast. Surf, relax, and unwind. Private beach access, outdoor shower, and jungle surroundings.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Nosara, Costa Rica",
    country: "Costa Rica",
    rooms: 3,
    categories: ["Beaches", "Nature", "Camping"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Cliffside Villa in Amalfi Coast",
    description: "Perched dramatically above the sea, this Italian cliffside villa features a private terrace, sea-view pool, and direct access to hidden coves via a private staircase.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1534430480872-3498386e7856?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3200,
    location: "Positano",
    country: "Italy",
    rooms: 3,
    categories: ["Beaches", "Swimming Pools", "Trending"],
    maxGuests: 6,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Zanzibar Beachfront Lodge",
    description: "Wake up to powdery white sand and turquoise Indian Ocean waters. Thatched-roof lodge, coral reef snorkeling, and a vibrant spice market nearby.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1100,
    location: "Zanzibar",
    country: "Tanzania",
    rooms: 2,
    categories: ["Beaches", "Nature", "Trending"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 3,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Overwater Bungalow in Bora Bora",
    description: "The classic dream — a luxury overwater bungalow above the lagoon in Bora Bora. Glass-floor panels, private deck, and turquoise water steps away.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 7500,
    location: "Bora Bora",
    country: "French Polynesia",
    rooms: 1,
    categories: ["Beaches", "Trending", "Swimming Pools"],
    maxGuests: 2,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── MOUNTAINS ───────────────────────────────────────────────────────────────
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies. Perfect for hiking, wildlife watching, and stargazing. Hot tub on the deck.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Banff",
    country: "Canada",
    rooms: 3,
    categories: ["Mountains", "Nature", "Ski Resorts"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 2,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Alpine Chalet in Swiss Alps",
    description: "Experience luxury mountain living in this stunning Alpine chalet. Panoramic mountain views, modern amenities, and access to world-class hiking trails.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2800,
    location: "Verbier",
    country: "Switzerland",
    rooms: 4,
    categories: ["Mountains", "Ski Resorts", "Nature"],
    maxGuests: 8,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Mountain Lodge in the Himalayas",
    description: "Stay in this beautiful mountain lodge with stunning Himalayan views. Guided mountain tours, local cuisine, and unparalleled trekking access.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464146072230-91cabc968266?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1100,
    location: "Manali",
    country: "India",
    rooms: 2,
    categories: ["Mountains", "Nature", "Camping"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 2,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Rocky Mountain Retreat Colorado",
    description: "Escape to this peaceful retreat surrounded by pine forests. Stone fireplace, mountain views, and access to hiking and fishing in the Rockies.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1300,
    location: "Colorado",
    country: "United States",
    rooms: 3,
    categories: ["Mountains", "Nature", "Ski Resorts"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 2,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Mountain Cabin in Smoky Mountains",
    description: "Cozy mountain cabin with spectacular valley views. Fireplace, wraparound deck, and modern kitchen — the perfect romantic getaway.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1486912500284-6f2462ba07ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 950,
    location: "Smoky Mountains",
    country: "United States",
    rooms: 1,
    categories: ["Mountains", "Nature", "Camping"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Andean Hacienda in Cusco",
    description: "Colonial-era hacienda nestled in the Sacred Valley of the Incas. Terracotta roofs, Andean textiles, and sweeping mountain panoramas. Machu Picchu day trips arranged.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1526392060635-9d6019884377?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600,
    location: "Cusco",
    country: "Peru",
    rooms: 5,
    categories: ["Mountains", "Nature", "Iconic Cities"],
    maxGuests: 10,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Atlas Mountain Kasbah",
    description: "A traditional Berber kasbah in Morocco's High Atlas Mountains. Rooftop terrace, panoramic peaks, and guided mule treks into remote Berber villages.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1539019033-2b48a1e64f3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 780,
    location: "Aït Benhaddou",
    country: "Morocco",
    rooms: 3,
    categories: ["Mountains", "Nature", "Camping"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── SWIMMING POOLS ───────────────────────────────────────────────────────────
  {
    title: "Tropical Villa with Infinity Pool in Phuket",
    description: "Escape to a tropical paradise with a private infinity pool. Ocean views, outdoor shower, and Thai-style pavilion for relaxation in Phuket.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    rooms: 4,
    categories: ["Swimming Pools", "Beaches", "Trending"],
    maxGuests: 8,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Modern Villa with Private Pool in Ibiza",
    description: "Stunning modern villa with a large private pool and outdoor entertainment area. Perfect for families seeking luxury and privacy on the White Isle.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2400,
    location: "Ibiza",
    country: "Spain",
    rooms: 5,
    categories: ["Swimming Pools", "Beaches", "Trending"],
    maxGuests: 10,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 4,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Luxury Estate with Olympic Pool in Beverly Hills",
    description: "Magnificent estate featuring an Olympic-sized swimming pool, pool house, and extensive gardens. Perfect for large gatherings and special events.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4500,
    location: "Beverly Hills",
    country: "United States",
    rooms: 7,
    categories: ["Swimming Pools", "Trending", "Iconic Cities"],
    maxGuests: 14,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Mediterranean Villa with Pool in Santorini",
    description: "Beautiful Mediterranean villa with heated pool and sea views. Outdoor kitchen, BBQ area, and sun loungers for ultimate relaxation in the Cyclades.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2800,
    location: "Santorini",
    country: "Greece",
    rooms: 4,
    categories: ["Swimming Pools", "Beaches", "Iconic Cities"],
    maxGuests: 8,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 5,
    maximumStay: 45,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Desert Retreat with Pool Oasis in Scottsdale",
    description: "Stunning desert retreat with a resort-style pool featuring a waterfall. Modern architecture, outdoor living spaces, and Sonoran desert views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3200,
    location: "Scottsdale",
    country: "United States",
    rooms: 5,
    categories: ["Swimming Pools", "Nature", "Trending"],
    maxGuests: 10,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Luxury Pool Villa in Ubud",
    description: "Rice-terrace views from a stunning jungle pool villa in Ubud's cultural heart. Daily breakfast, yoga pavilion, and a private chef available on request.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1700,
    location: "Ubud, Bali",
    country: "Indonesia",
    rooms: 3,
    categories: ["Swimming Pools", "Nature", "Trending"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Infinity Pool Penthouse in Cape Town",
    description: "Dramatic views of Table Mountain and the Atlantic Ocean from this penthouse infinity pool. Sleek interiors, rooftop bar, and walking distance to V&A Waterfront.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2600,
    location: "Cape Town",
    country: "South Africa",
    rooms: 3,
    categories: ["Swimming Pools", "Iconic Cities", "Beaches"],
    maxGuests: 6,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 4,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── CASTLES ─────────────────────────────────────────────────────────────────
  {
    title: "Historic Castle in Scottish Highlands",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Turrets, grand halls, and 50 acres of private grounds with roaming Highland cattle.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    rooms: 8,
    categories: ["Castles", "Nature", "Trending"],
    maxGuests: 16,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Medieval Castle in Loire Valley",
    description: "Experience medieval grandeur in this restored French castle. Original stone walls, tower rooms, and a moat. Perfect for a fairytale wedding or special event.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5000,
    location: "Loire Valley",
    country: "France",
    rooms: 10,
    categories: ["Castles", "Vineyards", "Trending"],
    maxGuests: 20,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Irish Castle Estate in County Cork",
    description: "Majestic Irish castle set on 100 acres of parkland. Grand dining hall, library, and multiple sitting rooms. Full staff service and private loch fishing.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 6000,
    location: "County Cork",
    country: "Ireland",
    rooms: 12,
    categories: ["Castles", "Nature", "Trending"],
    maxGuests: 24,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "German Castle with Alpine Views",
    description: "Romantic castle perched on a hilltop with stunning Alpine views. Medieval architecture, modern amenities, and a wine cellar stocked with local vintages.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4500,
    location: "Bavaria",
    country: "Germany",
    rooms: 9,
    categories: ["Castles", "Mountains", "Vineyards"],
    maxGuests: 18,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "English Manor Castle in the Cotswolds",
    description: "Elegant English manor house with castle features, formal gardens, tennis court, and indoor swimming pool. Set in the idyllic Cotswolds countryside.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3800,
    location: "Cotswolds",
    country: "United Kingdom",
    rooms: 8,
    categories: ["Castles", "Nature", "Swimming Pools"],
    maxGuests: 16,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 4,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Czech Baroque Castle in Bohemia",
    description: "Sleep in a real Baroque castle in the heart of Bohemia. Frescoed ceilings, a chapel, and a rose garden overlooking rolling Czech countryside.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2800,
    location: "Ceský Krumlov",
    country: "Czech Republic",
    rooms: 6,
    categories: ["Castles", "Iconic Cities", "Nature"],
    maxGuests: 12,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 3,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Portuguese Quinta Palace",
    description: "18th-century Portuguese quinta with azulejo-tiled walls, a grand ballroom, and vineyards visible from every window. Porto wine tasting and river cruises arranged.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Douro Valley",
    country: "Portugal",
    rooms: 7,
    categories: ["Castles", "Vineyards", "Nature"],
    maxGuests: 14,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── CAMPING ─────────────────────────────────────────────────────────────────
  {
    title: "Luxury Glamping Safari Tent",
    description: "Experience camping in style with this luxury glamping tent. Comfortable beds, private bathroom, and stunning nature views in the Serengeti.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 650,
    location: "Serengeti",
    country: "Tanzania",
    rooms: 1,
    categories: ["Camping", "Nature", "Trending"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 10,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "A-Frame Cabin in Big Sur",
    description: "Unique A-frame cabin perfect for glamping enthusiasts. Large windows framing the redwoods, cozy interior, and outdoor fire pit. Hiking trails nearby.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 720,
    location: "Big Sur",
    country: "United States",
    rooms: 1,
    categories: ["Camping", "Nature", "Beaches"],
    maxGuests: 3,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Yurt in the Montana Wilderness",
    description: "Traditional yurt offering a unique camping experience. Wood stove, comfortable furnishings, and panoramic mountain views. Off-grid living with solar power.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464207687429-7505649dae38?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 580,
    location: "Montana",
    country: "United States",
    rooms: 1,
    categories: ["Camping", "Nature", "Mountains"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Riverside Camping Pod in Lake District",
    description: "Modern camping pod by a peaceful river in England's most beloved national park. Comfortable beds, heating, and electricity for families wanting a cozy camping experience.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 480,
    location: "Lake District",
    country: "United Kingdom",
    rooms: 1,
    categories: ["Camping", "Nature", "Mountains"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 7,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Desert Camping in Wadi Rum",
    description: "Authentic desert camping with Bedouin-style tents in Wadi Rum's rose-red valley. Traditional meals, stargazing, and camel rides at sunrise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 550,
    location: "Wadi Rum",
    country: "Jordan",
    rooms: 1,
    categories: ["Camping", "Nature", "Trending"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 1,
    maximumStay: 5,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Geodesic Dome in Patagonia",
    description: "Sleep under a transparent dome with front-row views of Patagonian skies. Heated interior, en-suite bathroom, and guided treks to Torres del Paine just outside.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1454391304352-2bf4678b1a7a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600,
    location: "Torres del Paine",
    country: "Chile",
    rooms: 1,
    categories: ["Camping", "Nature", "Mountains"],
    maxGuests: 2,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 3,
    maximumStay: 10,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Lakeside Canvas Lodge in Canada",
    description: "Luxury canvas lodge on the shores of a pristine Alberta lake. Canoe and kayak included, guided fishing, campfire every evening, and spectacular aurora viewing.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504851149312-7a075b496cc7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 890,
    location: "Jasper",
    country: "Canada",
    rooms: 1,
    categories: ["Camping", "Nature", "Mountains"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── SKI RESORTS ─────────────────────────────────────────────────────────────
  {
    title: "Ski-In/Ski-Out Chalet in Verbier",
    description: "Hit the slopes right from your doorstep in this Swiss Alps chalet. Luxury mountain living with sauna, hot tub, and breathtaking alpine views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    rooms: 4,
    categories: ["Ski Resorts", "Mountains", "Trending"],
    maxGuests: 8,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Luxury Ski Chalet in Aspen",
    description: "Hit the slopes in style at this world-famous ski resort. Ski-in/ski-out access, wine cellar, private chef, and stunning mountain views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Aspen",
    country: "United States",
    rooms: 5,
    categories: ["Ski Resorts", "Mountains", "Trending"],
    maxGuests: 10,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Alpine Ski Lodge in Chamonix",
    description: "Cozy ski lodge at the base of Mont Blanc. Fireplace, ski storage, and après-ski lounge. Perfect for families and groups who live for the mountain.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Chamonix",
    country: "France",
    rooms: 6,
    categories: ["Ski Resorts", "Mountains", "Nature"],
    maxGuests: 12,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 5,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Modern Ski Apartment in Whistler",
    description: "Contemporary apartment with mountain views, heated floors, and a modern kitchen. Walking distance to ski lifts, restaurants, and Whistler Village shops.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1605540436563-5bca919ae27d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Whistler",
    country: "Canada",
    rooms: 3,
    categories: ["Ski Resorts", "Mountains", "Nature"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 4,
    maximumStay: 45,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Japanese Ski Resort Ryokan in Niseko",
    description: "Traditional Japanese inn at a world-class ski resort. Hot springs (onsen), tatami rooms, and authentic Japanese cuisine. A cultural skiing experience unlike any other.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Niseko",
    country: "Japan",
    rooms: 4,
    categories: ["Ski Resorts", "Mountains", "Trending"],
    maxGuests: 8,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Ski Chalet in Courchevel",
    description: "One of the world's most prestigious ski destinations. Slope-side chalet with concierge service, private ski instructor available, and Michelin-starred restaurants nearby.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5500,
    location: "Courchevel",
    country: "France",
    rooms: 6,
    categories: ["Ski Resorts", "Mountains", "Trending"],
    maxGuests: 12,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 7,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Luxury Ski Lodge in Queenstown",
    description: "Southern Hemisphere skiing at its finest. Boutique lodge with stunning views of the Remarkables mountain range, spa, and fine dining in Queenstown minutes away.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1418985991508-e47386d96a71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2600,
    location: "Queenstown",
    country: "New Zealand",
    rooms: 4,
    categories: ["Ski Resorts", "Mountains", "Nature"],
    maxGuests: 8,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 4,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── VINEYARDS ────────────────────────────────────────────────────────────────
  {
    title: "Tuscan Vineyard Villa near Florence",
    description: "Experience the charm of Tuscany in this beautifully restored villa surrounded by vineyards. Wine tasting tours, cooking classes, and stunning countryside views included.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Florence",
    country: "Italy",
    rooms: 5,
    categories: ["Vineyards", "Nature", "Trending"],
    maxGuests: 10,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 5,
    maximumStay: 90,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Napa Valley Wine Estate",
    description: "Luxurious estate in the heart of Napa Valley. Private wine cellar, vineyard tours, and a gourmet kitchen. Perfect for wine enthusiasts and special celebrations.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506377585622-bedcbb5a8b35?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Napa Valley",
    country: "United States",
    rooms: 6,
    categories: ["Vineyards", "Trending", "Swimming Pools"],
    maxGuests: 12,
    instantBooking: false,
    refundPolicy: "strict",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Provence Vineyard Farmhouse",
    description: "Charming farmhouse surrounded by lavender fields and vineyards in Provence. Stone walls, outdoor dining, and wine tasting. Authentic French countryside living.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1900,
    location: "Provence",
    country: "France",
    rooms: 3,
    categories: ["Vineyards", "Nature", "Iconic Cities"],
    maxGuests: 6,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 4,
    maximumStay: 60,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Spanish Vineyard Retreat in Rioja",
    description: "Beautiful retreat in Spain's famous Rioja wine region. Wine cellar, panoramic vineyard views, and wine tasting and local gastronomy tours included.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587061949409-02df41d5e562?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2100,
    location: "La Rioja",
    country: "Spain",
    rooms: 4,
    categories: ["Vineyards", "Nature", "Iconic Cities"],
    maxGuests: 8,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 45,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "South African Wine Farm in Stellenbosch",
    description: "Stunning wine farm in Cape Winelands featuring Cape Dutch architecture, mountain views, and award-winning wines. Farm-to-table dining and cellar tours.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1700,
    location: "Stellenbosch",
    country: "South Africa",
    rooms: 4,
    categories: ["Vineyards", "Nature", "Trending"],
    maxGuests: 8,
    instantBooking: true,
    refundPolicy: "moderate",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Argentine Vineyard Estancia in Mendoza",
    description: "Grand estancia surrounded by high-altitude Malbec vineyards. Horseback riding, asado by the fire, private sommelier, and views of the snow-capped Andes.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2300,
    location: "Mendoza",
    country: "Argentina",
    rooms: 6,
    categories: ["Vineyards", "Mountains", "Nature"],
    maxGuests: 12,
    instantBooking: false,
    refundPolicy: "moderate",
    minimumStay: 4,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "New Zealand Vineyard Cottage in Marlborough",
    description: "Charming cottage nestled among Sauvignon Blanc vines in Marlborough's wine heartland. Bike to cellar doors, kayak on Queen Charlotte Sound, and watch the Southern Cross at night.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "Marlborough",
    country: "New Zealand",
    rooms: 2,
    categories: ["Vineyards", "Nature", "Beaches"],
    maxGuests: 4,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 3,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },

  // ─── ROOMS ────────────────────────────────────────────────────────────────────
  {
    title: "Boutique Room in Kyoto Machiya",
    description: "A private room in a lovingly restored 100-year-old Kyoto townhouse. Tatami floors, sliding shoji screens, and a shared Zen garden. Walk to Gion and Nishiki Market.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 420,
    location: "Kyoto",
    country: "Japan",
    rooms: 1,
    categories: ["Rooms", "Iconic Cities", "Trending"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Cozy Studio in Trastevere, Rome",
    description: "Sun-filled studio apartment in Rome's most romantic neighbourhood. Cobblestone streets below, a private terrace above, and the best carbonara spot around the corner.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1515542622106-078bda9c12a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 380,
    location: "Rome",
    country: "Italy",
    rooms: 1,
    categories: ["Rooms", "Iconic Cities", "Nature"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Private Room in Haveli, Jaipur",
    description: "A private suite inside a 300-year-old painted haveli in the Pink City. Arched windows, mirror-work walls, rooftop dinners, and a local family welcoming you in.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 290,
    location: "Jaipur",
    country: "India",
    rooms: 1,
    categories: ["Rooms", "Iconic Cities", "Trending"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Garden Suite in Cape Malay Quarter",
    description: "A sunny en-suite garden room in a brightly painted Cape Malay house on the slopes of Signal Hill. Bo-Kaap's painted houses, vibrant culture, and Table Mountain views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 260,
    location: "Cape Town",
    country: "South Africa",
    rooms: 1,
    categories: ["Rooms", "Iconic Cities", "Nature"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Treehouse Room in Chiang Mai",
    description: "A quirky treehouse bedroom elevated into the jungle canopy on the outskirts of Chiang Mai. En-suite hammock, morning elephant sounds, and a shared infinity pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 310,
    location: "Chiang Mai",
    country: "Thailand",
    rooms: 1,
    categories: ["Rooms", "Nature", "Swimming Pools"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Historic Room in Medina, Fez",
    description: "A heritage room deep in the ancient medina of Fez. Hand-painted tiles, cedar ceilings, and the sounds of the world's oldest living university drifting through the window.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 200,
    location: "Fez",
    country: "Morocco",
    rooms: 1,
    categories: ["Rooms", "Iconic Cities", "Trending"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 14,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Converted Barn Room in Tuscany",
    description: "A rustic-luxe private room in a centuries-old stone barn conversion on a working Chianti estate. Vineyard views, shared pool, and breakfast with homemade jam.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464146072230-91cabc968266?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 350,
    location: "Chianti",
    country: "Italy",
    rooms: 1,
    categories: ["Rooms", "Vineyards", "Nature"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 21,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Guesthouse Room in Petra",
    description: "Stay just outside the ancient Nabataean city of Petra in a family-run cave guesthouse. Stone-cut interiors, Bedouin breakfasts, and a front-row seat to the Treasury at sunrise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1548013146-72479768bada?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 180,
    location: "Petra",
    country: "Jordan",
    rooms: 1,
    categories: ["Rooms", "Iconic Cities", "Camping"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 10,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Houseboat Room in Alleppey",
    description: "Your own private cabin aboard a traditional Kerala rice-boat drifting through the backwaters. Home-cooked Keralan meals, paddy field views, and total tranquility.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 320,
    location: "Alleppey",
    country: "India",
    rooms: 1,
    categories: ["Rooms", "Nature", "Beaches"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 1,
    maximumStay: 7,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
  {
    title: "Private Room in a Buenos Aires Palacio",
    description: "A sumptuous private room in a restored Belle Époque palacio in Palermo Soho. French doors opening onto a wrought-iron balcony, rooftop pool, and tango just downstairs.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 270,
    location: "Buenos Aires",
    country: "Argentina",
    rooms: 1,
    categories: ["Rooms", "Iconic Cities", "Swimming Pools"],
    maxGuests: 2,
    instantBooking: true,
    refundPolicy: "flexible",
    minimumStay: 2,
    maximumStay: 30,
    owner: "68f9fa6c7dc2f3eab246d675",
  },
];

module.exports = { data: sampleListings };